### ISSUE TITLE
jpf.properties incorrectly defines the jpf-nhandler.classpath property

### ISSUE THREAD

**Issue by matthewwalk** [javapathfinder/jpf-nhandler#1]
## Description
When using ANT version 1.10.10 the resulting jar file built is named `jpf-nhandler.jar` ; however, the jpf.properties file defines it to be `jpf-nhandler-classes.jar`

## Steps to Reproduce
1. Install ANT 1.10.10 binaries
2. Clone jpf-nhandler
3. Build jpf-nhandler using the `ant` command in the jpf-nhandler root directory
4. View the discrepancy

## Proposed Solution
Just update the definition in the `jpf.properties` file as follows:
```
jpf-nhandler.classpath =\
   ${jpf-nhandler}/build/jpf-nhandler.jar;\
   ${jpf-nhandler}/build/examples
```

**Comment by cyrille-artho** [comment]
Thank you for this hint. This was indeed wrong (but did not cause issues if `~/.jpf/site.properties` is set correctly, hence we never noticed). I've fixed this now.
